#!groovy

// Copyright (c) 2020 ETH Zurich
//
// SPDX-License-Identifier: BSL-1.0
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

pipeline {
    agent {
        node {
            label 'ssl_daintvm1'
        }
    }
    triggers {
        cron('0 0 * * *')
    }
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: "14",
                numToKeepStr: "50",
                artifactDaysToKeepStr: "14",
                artifactNumToKeepStr: "50"
            )
        )
    }
    environment {
        SPACK_ROOT = '/apps/daint/SSL/HPX/spack'
        GITHUB_TOKEN = credentials('STELLARBOT_GITHUB_TOKEN')
    }
    stages {
        stage('checkout') {
            steps {
                dir('kokkos-hpx-ci') {
                    checkout scm
                    echo "Running ${env.BUILD_ID} on ${env.JENKINS_URL}"
                }
            }
        }
        stage('build') {
            matrix {
                axes {
                    axis {
                        name 'configuration_name'
                        values 'gcc', 'clang'
                    }
                    axis {
                        name 'build_type'
                        values 'Release', 'Debug'
                    }
                    axis {
                        name 'cuda'
                        values 'OFF'
                    }
                    axis {
                        name 'hpx_version'
                        values '1.7.0'
                    }
                    axis {
                        name 'kokkos_version'
                        values 'hpx-update-deprecations'
                    }
                    axis {
                         name 'async_dispatch'
                         values 'ON' , 'OFF'
                    }
                    axis {
                         name 'hpx_backend_implementation'
                         values '1'
                    }
                }
                stages {
                    stage('build') {
                        steps {
                            dir('kokkos-hpx-ci') {
                                sh '''
                                #!/bin/bash -l
                                .jenkins/cscs/entry.sh
                                '''
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'kokkos-hpx-ci/jenkins-kokkos-hpx-ci-*', fingerprint: true
            archiveArtifacts artifacts: 'kokkos-hpx-ci/*-Testing/**', fingerprint: true
        }
    }
}
